services:
  api:
    container_name: api-back
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:Chivas12.@db:5432/integradora
      - JWT_SECRET=eq2
      - JWT_EXPIRES_IN=1h
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /app/node_modules
    networks:
      - app-network
  
  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Chivas12.
      POSTGRES_DB: integradora
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

volumes:
  pgdata_alt:

networks:
  app-network:
    name: app-network
    driver: bridge
